05 Bugfix check camel and _ case before inserting into database
lingoda/EntityAudit pull request #5
Opened 2020-11-02 18:22 UTC by michealmouner

2020-11-03 08:56 UTC, TamasSzigeti requested changes

2020-11-03 08:56 UTC, TamasSzigeti commented on src/SimpleThings/EntityAudit/AuditConfiguration.php
>      {
This is just random guessing of what the column name could be, right? What if I have
```
/** @ORM\Column(name="somethingCompletelyDifferent") */
private $fieldName;
```
?

2020-11-03 09:39 UTC, michealmouner commented on src/SimpleThings/EntityAudit/AuditConfiguration.php
>      {
mhmmm
I will send the ignored columns as `key => value`  then

2020-11-04 13:40 UTC, closed without merging

2020-11-04 13:40 UTC, michealmouner commented
I  created a new PR